/*Table structure for table `medratests` */

CREATE TABLE `medratests`
(
    `Field1` varchar(36) default NULL,
    KEY `NewIndex9` (`Field1`)
) ENGINE = InnoDB
  DEFAULT CHARSET = latin1;

/*Data for the table `medratests` */

insert into `medratests`(`Field1`)
values ('17 ketosteroids urine'),
       ('17 ketosteroids urine'),
       ('2,5-oligoadenylate synthetase test'),
       ('2,5-oligoadenylate synthetase test'),
       ('5-hiaa urine'),
       ('5-hydroxyindolacetic acid'),
       ('5-hydroxyindolacetic acid'),
       ('5-hydroxyindolacetic acid in urine'),
       ('5-hydroxyindolacetic acid in urine'),
       ('5nucleotidase'),
       ('5nucleotidase'),
       ('a/g ratio'),
       ('absolute neutrophil count'),
       ('acetaminophen'),
       ('acetoacetate'),
       ('acetone'),
       ('acetone urine'),
       ('acetylcholinesterase'),
       ('acid base balance'),
       ('acid base balance'),
       ('acid fast stain'),
       ('acid fast stain'),
       ('acid hemolysin test'),
       ('acid hemolysin test'),
       ('acid phos'),
       ('acid phosphatase'),
       ('acid-base balance'),
       ('acth'),
       ('activated coagulation time'),
       ('activated partial thromboplastin tim'),
       ('activated partial thromboplastin tim'),
       ('activated protein c resistance test'),
       ('activated protein c resistance test'),
       ('adenovirus serology nos'),
       ('adenovirus test'),
       ('adh'),
       ('adrenocorticotropic hormone'),
       ('adrenocorticotropin'),
       ('afp amniotic fluid'),
       ('alanine aminotransferase'),
       ('alanine aminotransferase'),
       ('albumin'),
       ('albumin csf'),
       ('albumin csf'),
       ('albumin globulin ratio'),
       ('albumin globulin ratio'),
       ('albumin urine'),
       ('albumin urine'),
       ('aldolase'),
       ('aldolase'),
       ('aldosterone'),
       ('aldosterone urine'),
       ('aldosterone urine'),
       ('alk phos'),
       ('alk phosph'),
       ('alkaline phosphatase'),
       ('alkaline reserve'),
       ('alpha 1 fetoprotein'),
       ('alpha 1 fetoprotein amniotic fluid'),
       ('alpha 1 foetoprotein'),
       ('alpha 1 foetoprotein'),
       ('alpha 1 foetoprotein amniotic fluid'),
       ('alpha 1 foetoprotein amniotic fluid'),
       ('alpha 1 globulin'),
       ('alpha 1 globulin'),
       ('alpha 1 microglobulin urine'),
       ('alpha 1 microglobulin urine'),
       ('alpha 2 antiplasmin'),
       ('alpha 2 globulin'),
       ('alpha 2 globulin'),
       ('alpha hydroxybutyrate dehydrogenase'),
       ('alpha hydroxybutyrate dehydrogenase'),
       ('alpha tumor necrosis factor'),
       ('alpha tumour necrosis factor'),
       ('alpha tumour necrosis factor'),
       ('alpha-1 anti-trypsin'),
       ('alpha-1 anti-trypsin'),
       ('alpha-2 macroglobulin'),
       ('alpha-2 macroglobulin'),
       ('alphafetoprotein'),
       ('alphafetoprotein amniotic fluid'),
       ('alphafoetoprotein'),
       ('alphafoetoprotein amniotic fluid'),
       ('alphaglobulin'),
       ('aluminium'),
       ('aluminum'),
       ('amebic serology'),
       ('amino acid level'),
       ('amino acid level'),
       ('aminolevulinic acid urine'),
       ('ammonia'),
       ('ammonia'),
       ('amoebic serology'),
       ('amoebic serology'),
       ('amphetamines'),
       ('amphetamines'),
       ('amylase'),
       ('ana'),
       ('analgesic drug level'),
       ('analgesic drug level'),
       ('anca'),
       ('androgens'),
       ('androgens'),
       ('androgens nos'),
       ('angiotensin converting enzyme'),
       ('angiotensin converting enzyme'),
       ('angiotensin i'),
       ('angiotensin i'),
       ('angiotensin ii'),
       ('angiotensin ii'),
       ('anion gap'),
       ('anion gap'),
       ('anp'),
       ('anti-dna antibodies'),
       ('anti-dna antibodies nos'),
       ('anti-dna antibody'),
       ('anti-erythropoietin antibody'),
       ('anti-erythropoietin antibody'),
       ('anti-factor viii antibodies'),
       ('anti-gad antibody'),
       ('anti-gad antibody'),
       ('anti-gbm antibody'),
       ('anti-glomerular basement membrane an'),
       ('anti-glomerular basement membrane an'),
       ('anti-hbe antibody'),
       ('anti-hbe antibody'),
       ('anti-hbs antibody'),
       ('anti-hbs antibody'),
       ('anti-hiv test (eia)'),
       ('anti-insulin antibody'),
       ('anti-insulin antibody'),
       ('anti-islet cell antibody'),
       ('anti-islet cell antibody'),
       ('anti-la antibody'),
       ('anti-platelet antibodies'),
       ('anti-platelet antibody'),
       ('anti-platelet antibody'),
       ('anti-ro antibody'),
       ('anti-sperm antibody'),
       ('anti-sperm antibody'),
       ('anti-ss-a antibody'),
       ('anti-ss-a antibody'),
       ('anti-ss-b antibody'),
       ('anti-ss-b antibody'),
       ('anti-streptococcus dnase b test'),
       ('anti-thyroid antibodies'),
       ('anti-thyroid antibody'),
       ('anti-thyroid antibody'),
       ('antiacetylcholine receptor antibody'),
       ('antiacetylcholine receptor antibody'),
       ('antibiotic level'),
       ('antibiotic level'),
       ('antibodies anticardiolipin'),
       ('antibodies cardiolipin'),
       ('antibody test'),
       ('antibody test'),
       ('anticardiolipin antibodies'),
       ('anticoagulation drug level'),
       ('anticoagulation drug level'),
       ('anticonvulsant drug level'),
       ('anticonvulsant drug level'),
       ('antidepressant drug clearance'),
       ('antidepressant drug clearance'),
       ('antidepressant drug clearance nos'),
       ('antidepressant drug level'),
       ('antidepressant drug level'),
       ('antidiuretic hormone'),
       ('antiglobulin test direct'),
       ('antiglobulin test indirect'),
       ('antihaemophilic factor'),
       ('antihemophilic factor'),
       ('antihuman immunodeficiency virus ant'),
       ('antihuman immunodeficiency virus ant'),
       ('antimicrobial susceptibility test'),
       ('antimicrobial susceptibility test'),
       ('antimitochondrial antibody'),
       ('antimitochondrial antibody'),
       ('antimony'),
       ('antineutrophil cytoplasmic antibody'),
       ('antineutrophil cytoplasmic antibody'),
       ('antinuclear antibody'),
       ('antinuclear antibody'),
       ('antinuclear factor'),
       ('antiphospholipid antibodies'),
       ('antiphospholipid antibodies'),
       ('antipsychotic drug level'),
       ('antipsychotic drug level'),
       ('antistreptolysin'),
       ('antistreptolysin antibodies'),
       ('antistreptolysin titre'),
       ('antithrombin iii'),
       ('antithrombin iii'),
       ('antiviral drug level'),
       ('antiviral drug level'),
       ('apa'),
       ('apo a1'),
       ('apo b'),
       ('apo-a1'),
       ('apo-b'),
       ('apolipoprotein'),
       ('apolipoprotein'),
       ('apolipoprotein a-i'),
       ('apolipoprotein a-i'),
       ('apolipoprotein a-ii'),
       ('apolipoprotein a-ii'),
       ('apolipoprotein b'),
       ('apolipoprotein b'),
       ('apolipoprotein b/apolipoprotein a-1'),
       ('apolipoprotein b/apolipoprotein a-1'),
       ('apolipoprotein c'),
       ('apolipoprotein c'),
       ('apoprotein a1'),
       ('apoprotein b'),
       ('aptt'),
       ('arsenic in serum'),
       ('arterial blood ph'),
       ('ascorbate'),
       ('ascorbic acid'),
       ('aso titre'),
       ('asp transferase'),
       ('aspartate aminotransferase'),
       ('aspartate aminotransferase'),
       ('aspartate transferase'),
       ('aspiration bursa'),
       ('aspiration bursa'),
       ('aspt'),
       ('atrial natriuretic peptide'),
       ('atrial natriuretic peptide'),
       ('auto-antibody response'),
       ('autoantibody response'),
       ('autoantibody test'),
       ('autoantibody test'),
       ('b-lymphocyte count'),
       ('b-lymphocyte count'),
       ('b-type natriuretic peptide'),
       ('b. pertussis serology'),
       ('b2 microglobulin'),
       ('babesia dna test'),
       ('babesia serology'),
       ('bacteria blood test'),
       ('bacteria blood test'),
       ('bacteria identification and serology'),
       ('bacteria nos sputum identified'),
       ('bacteria sputum identified'),
       ('bacteria sputum identified'),
       ('bacteria stool test'),
       ('bacteria stool test'),
       ('bacteria urine'),
       ('bacteria urine'),
       ('bacterial culture'),
       ('bacterial culture'),
       ('bacterial dna test'),
       ('bacterial dna test'),
       ('band neutrophil count'),
       ('band neutrophil count'),
       ('band neutrophil percentage'),
       ('band neutrophil percentage'),
       ('barbiturates'),
       ('barbiturates'),
       ('base excess'),
       ('base excess'),
       ('basophil count'),
       ('basophil count'),
       ('basophil morphology'),
       ('basophil morphology'),
       ('basophil percentage'),
       ('basophil percentage'),
       ('basophils'),
       ('bence jones protein urine'),
       ('bence jones protein urine'),
       ('beryllium'),
       ('beta 2 globulin'),
       ('beta 2 globulin'),
       ('beta 2 microglobulin'),
       ('beta 2 microglobulin'),
       ('beta globulin'),
       ('beta globulin'),
       ('beta-n-acetyl-d-glucosaminidase'),
       ('beta-n-acetyl-d-glucosaminidase'),
       ('betaglobulin'),
       ('betahydroxybutyrate'),
       ('bgp'),
       ('bicarbonate'),
       ('bile culture'),
       ('bile culture'),
       ('bile duct pressure'),
       ('bile duct pressure'),
       ('bilirubin'),
       ('bilirubin conjugated'),
       ('bilirubin conjugated'),
       ('bilirubin direct'),
       ('bilirubin non-glucuronides'),
       ('bilirubin total'),
       ('bilirubin unconjugated'),
       ('bilirubin urine'),
       ('bilirubin urine'),
       ('bilirubinuria'),
       ('bilirubinuria'),
       ('biopsy cartilage'),
       ('biopsy cartilage'),
       ('biopsy muscle'),
       ('biopsy muscle'),
       ('biopsy of bone excl marrow'),
       ('biopsy of cervical gland'),
       ('biopsy retina'),
       ('biopsy retina'),
       ('biopsy sclera'),
       ('biopsy sclera'),
       ('blast cells'),
       ('blast cells'),
       ('blast cells nos'),
       ('bleeding time'),
       ('bleeding time'),
       ('blood 1,25-dihydroxycholecalciferol'),
       ('blood 1,25-dihydroxycholecalciferol'),
       ('blood 25-hydroxy vitamin d2'),
       ('blood 25-hydroxycholecalciferol'),
       ('blood 25-hydroxycholecalciferol'),
       ('blood acth'),
       ('blood albumin'),
       ('blood albumin'),
       ('blood alcohol'),
       ('blood alcohol'),
       ('blood aldosterone'),
       ('blood aldosterone'),
       ('blood alkaline phosphatase intestine'),
       ('blood alkaline phosphatase placental'),
       ('blood alpha 2 heremans-schmid glycop'),
       ('blood alpha 2 heremans-schmid glycop'),
       ('blood alpha amylase'),
       ('blood aluminium'),
       ('blood aluminium'),
       ('blood aluminum'),
       ('blood amino acid level'),
       ('blood amino acid level'),
       ('blood amphetamines'),
       ('blood amylase'),
       ('blood amylase'),
       ('blood androstenedione'),
       ('blood androstenedione'),
       ('blood antidiuretic hormone'),
       ('blood antidiuretic hormone'),
       ('blood antimony'),
       ('blood antimony'),
       ('blood barbiturates'),
       ('blood basophils'),
       ('blood beryllium'),
       ('blood beryllium'),
       ('blood beta human chorionic gonadotro'),
       ('blood bicarbonate'),
       ('blood bicarbonate'),
       ('blood bilirubin'),
       ('blood bilirubin'),
       ('blood bilirubin direct'),
       ('blood bilirubin indirect'),
       ('blood bilirubin total'),
       ('blood bilirubin unconjugated'),
       ('blood bilirubin unconjugated'),
       ('blood bromide'),
       ('blood bromide'),
       ('blood cadmium'),
       ('blood cadmium'),
       ('blood caffeine'),
       ('blood caffeine'),
       ('blood calcitonin'),
       ('blood calcitonin'),
       ('blood calcium'),
       ('blood calcium'),
       ('blood cannabinoids'),
       ('blood cannabinoids'),
       ('blood cannabinoids nos'),
       ('blood carbon dioxide'),
       ('blood carbon monoxide'),
       ('blood carbon monoxide'),
       ('blood catecholamines'),
       ('blood catecholamines'),
       ('blood chloride'),
       ('blood chloride'),
       ('blood cholesterol'),
       ('blood cholesterol'),
       ('blood cholinesterase'),
       ('blood cholinesterase'),
       ('blood chromium'),
       ('blood chromium'),
       ('blood citric acid'),
       ('blood citric acid'),
       ('blood copper'),
       ('blood copper'),
       ('blood corticosterone'),
       ('blood corticosterone'),
       ('blood corticotrophin'),
       ('blood corticotrophin'),
       ('blood cortisol'),
       ('blood cortisol'),
       ('blood count'),
       ('blood count'),
       ('blood counts nec'),
       ('blood creatine'),
       ('blood creatine'),
       ('blood creatine phosphokinase'),
       ('blood creatine phosphokinase'),
       ('blood creatine phosphokinase bb'),
       ('blood creatine phosphokinase bb'),
       ('blood creatine phosphokinase mb'),
       ('blood creatine phosphokinase mb'),
       ('blood creatine phosphokinase mm'),
       ('blood creatine phosphokinase mm'),
       ('blood creatinine'),
       ('blood creatinine'),
       ('blood culture'),
       ('blood culture'),
       ('blood cyanide'),
       ('blood cyanide'),
       ('blood elastase'),
       ('blood elastase'),
       ('blood electrolytes'),
       ('blood electrolytes'),
       ('blood electrolytes nos'),
       ('blood erythropoietin'),
       ('blood erythropoietin'),
       ('blood estradiol'),
       ('blood estrogen'),
       ('blood estrone'),
       ('blood ethanol'),
       ('blood ethanol'),
       ('blood fibrinogen'),
       ('blood fibrinogen'),
       ('blood folate'),
       ('blood folate'),
       ('blood folic acid'),
       ('blood follicle stimulating hormone'),
       ('blood follicle stimulating hormone'),
       ('blood galactose'),
       ('blood galactose'),
       ('blood gamma amylase'),
       ('blood gas and acid base analyses'),
       ('blood gases'),
       ('blood gases'),
       ('blood gases nos'),
       ('blood gastrin'),
       ('blood gastrin'),
       ('blood glucagon'),
       ('blood glucagon'),
       ('blood glucose'),
       ('blood glucose'),
       ('blood glutamic-oxaloacetic transfera'),
       ('blood glycoalbumin'),
       ('blood gonadotrophin'),
       ('blood gonadotrophin'),
       ('blood grouping'),
       ('blood grouping'),
       ('blood grouping and cross-matching an'),
       ('blood growth hormone'),
       ('blood growth hormone'),
       ('blood heavy metal test'),
       ('blood heavy metal test'),
       ('blood homocysteine'),
       ('blood homocysteine'),
       ('blood human chorionic gonadotrophin'),
       ('blood human chorionic gonadotropin'),
       ('blood human chorionic gonadotropin'),
       ('blood immunoglobulin a'),
       ('blood immunoglobulin a'),
       ('blood immunoglobulin d'),
       ('blood immunoglobulin d'),
       ('blood immunoglobulin e'),
       ('blood immunoglobulin e'),
       ('blood immunoglobulin g'),
       ('blood immunoglobulin g'),
       ('blood immunoglobulin m'),
       ('blood immunoglobulin m'),
       ('blood insulin'),
       ('blood insulin'),
       ('blood insulin c-peptide'),
       ('blood iron'),
       ('blood iron'),
       ('blood isopropanol'),
       ('blood isopropanol'),
       ('blood isotope clearance'),
       ('blood isotope clearance'),
       ('blood ketone body'),
       ('blood ketone body'),
       ('blood lactate dehydrogenase'),
       ('blood lactate dehydrogenase'),
       ('blood lactic acid'),
       ('blood lactic acid'),
       ('blood ldh'),
       ('blood lead'),
       ('blood lead'),
       ('blood luteinising hormone'),
       ('blood luteinising hormone'),
       ('blood magnesium'),
       ('blood magnesium'),
       ('blood manganese'),
       ('blood mercury'),
       ('blood mercury'),
       ('blood methaemoglobin'),
       ('blood methaemoglobin'),
       ('blood methanol'),
       ('blood methanol'),
       ('blood methemoglobin'),
       ('blood oestradiol'),
       ('blood oestrogen'),
       ('blood oestrogen'),
       ('blood oestrone'),
       ('blood opiates'),
       ('blood osmolarity'),
       ('blood osmolarity'),
       ('blood pancreatic amylase'),
       ('blood parathyroid hormone'),
       ('blood parathyroid hormone'),
       ('blood ph'),
       ('blood ph'),
       ('blood ph nos'),
       ('blood phosphate'),
       ('blood phosphorus'),
       ('blood phosphorus'),
       ('blood placental gonadotrophins'),
       ('blood potassium'),
       ('blood potassium'),
       ('blood progesterone'),
       ('blood proinsulin'),
       ('blood proinsulin'),
       ('blood prolactin'),
       ('blood prolactin'),
       ('blood protein / albumin'),
       ('blood protein electrophoresis'),
       ('blood pyruvic acid'),
       ('blood pyruvic acid'),
       ('blood salivary amylase'),
       ('blood selenium'),
       ('blood selenium'),
       ('blood sodium'),
       ('blood sodium'),
       ('blood test'),
       ('blood test'),
       ('blood test nos'),
       ('blood testosterone'),
       ('blood testosterone'),
       ('blood testosterone free'),
       ('blood testosterone free'),
       ('blood thrombin'),
       ('blood thrombin'),
       ('blood thromboplastin'),
       ('blood thromboplastin'),
       ('blood thyroid stimulating hormone'),
       ('blood thyroid stimulating hormone'),
       ('blood triglycerides'),
       ('blood triglycerides'),
       ('blood tryptase'),
       ('blood typing'),
       ('blood urea'),
       ('blood urea'),
       ('blood urea nitrogen'),
       ('blood urea nitrogen/creatinine ratio'),
       ('blood urea nitrogen/creatinine ratio'),
       ('blood uric acid'),
       ('blood uric acid'),
       ('blood zinc'),
       ('blood zinc'),
       ('bone gla protein'),
       ('bone marrow and immune tissue analys'),
       ('bone marrow examination'),
       ('bone marrow myelogram'),
       ('bone marrow myelogram'),
       ('bone marrow scintigraphy'),
       ('borrelia burgdorferi immunoglobulin'),
       ('borrelia burgdorferi immunoglobulin'),
       ('borrelia burgdorferi serology'),
       ('borrelia burgdorferi serology'),
       ('br'),
       ('br-'),
       ('brahma forest enterovirus antibody t'),
       ('brain natriuretic peptide'),
       ('brain natriuretic peptide'),
       ('breath alcohol test'),
       ('breath alcohol test'),
       ('bromide'),
       ('bromosulphthalein test'),
       ('bromosulphthalein test'),
       ('bronchial dilator level nos'),
       ('brucella serology'),
       ('brucella serology'),
       ('bun'),
       ('bursa aspiration'),
       ('bursal aspiration'),
       ('butanol-extractable iodine'),
       ('butanol-extractable iodine'),
       ('c-reactive protein'),
       ('c-reactive protein'),
       ('c-telopeptide'),
       ('c-telopeptide'),
       ('c-telopeptide serum'),
       ('c1 esterase inhibitor test'),
       ('c1 esterase inhibitor test'),
       ('c1 inhibitor functional assay'),
       ('c1q binding assay'),
       ('ca 125'),
       ('ca 15-3'),
       ('ca 19-9'),
       ('ca 27.29'),
       ('ca 549'),
       ('ca++'),
       ('cadmium'),
       ('caffeine'),
       ('calcitonin'),
       ('calcium'),
       ('calcium ionised'),
       ('calcium ionised'),
       ('calcium ionized'),
       ('calcium phosphate product'),
       ('calcium phosphate product'),
       ('calcium total'),
       ('calcium urine (24 hour sample)'),
       ('calcium/creatinine ratio'),
       ('campylobacter like organism test'),
       ('cancer antigen 125'),
       ('cancer antigen 15-3'),
       ('cancer antigen 19-9'),
       ('cancer antigen 27.29'),
       ('cancer antigen 549'),
       ('candida iga'),
       ('candida igg'),
       ('candida igm'),
       ('candida serology'),
       ('candida serology'),
       ('cannabinoids'),
       ('capillary fragility'),
       ('capillary fragility'),
       ('capillary fragility test'),
       ('capillary fragility test'),
       ('capillary resistance test'),
       ('carbohydrate antigen 125'),
       ('carbohydrate antigen 125'),
       ('carbohydrate antigen 15-3'),
       ('carbohydrate antigen 15-3'),
       ('carbohydrate antigen 19-9'),
       ('carbohydrate antigen 19-9'),
       ('carbohydrate antigen 27.29'),
       ('carbohydrate antigen 27.29'),
       ('carbohydrate antigen 549'),
       ('carbohydrate antigen 549'),
       ('carbohydrate tolerance analyses (inc'),
       ('carbon dioxide'),
       ('carbon dioxide'),
       ('carbon dioxide total'),
       ('carbon monoxide'),
       ('carboxyhaemoglobin'),
       ('carboxyhaemoglobin'),
       ('carboxyhemoglobin'),
       ('carcinoembryonic antigen'),
       ('carcinoembryonic antigen'),
       ('cardiac enzymes'),
       ('cardiac enzymes'),
       ('cardiac enzymes nos'),
       ('cardiac troponin'),
       ('cardiac troponin i'),
       ('cardiac troponin t'),
       ('cardioactive drug level'),
       ('cardioactive drug level'),
       ('cardioactive drug level nos'),
       ('cardiolipin antibodies'),
       ('cardiolipin antibody'),
       ('cardiolipin antibody'),
       ('cardiolipin immunoglobulin g'),
       ('cardiolipin immunoglobulin m'),
       ('carnitine'),
       ('carnitine'),
       ('carotene'),
       ('carotene'),
       ('cartilage biopsy'),
       ('catecholamines'),
       ('catecholamines urine'),
       ('catecholamines urine'),
       ('cbc'),
       ('cd4/cd8 ratio'),
       ('cd4/cd8 ratio'),
       ('cell marker'),
       ('cell marker'),
       ('cell marker procedures'),
       ('cephalin flocculation'),
       ('cephalin flocculation'),
       ('cerebrospinal fluid cell count nos'),
       ('cerebrospinal fluid electrophoresis'),
       ('cerebrospinal fluid glucose'),
       ('cerebrospinal fluid granulocyte coun'),
       ('cerebrospinal fluid lymphocyte count'),
       ('cerebrospinal fluid oligoclonal band'),
       ('cerebrospinal fluid ph'),
       ('cerebrospinal fluid protein'),
       ('cerebrospinal fluid tests (excl micr'),
       ('cerebrospinal fluid white cell count'),
       ('ceruloplasmin'),
       ('ceruloplasmin'),
       ('cervical culture'),
       ('cervical cytology'),
       ('charcot-leyden crystals'),
       ('charcot-leyden crystals'),
       ('chemistry analyses nec'),
       ('chemotherapeutic drug level'),
       ('chemotherapeutic drug level'),
       ('chemotherapeutic drug level nos'),
       ('chitotriosidase'),
       ('chitotriosidase'),
       ('chlamydia serology'),
       ('chlamydia serology'),
       ('chloride'),
       ('cholesterol'),
       ('cholesterol analyses'),
       ('cholesterol total'),
       ('cholinesterase'),
       ('christmas factor'),
       ('chromium'),
       ('chromosomal analysis'),
       ('chromosomal analysis'),
       ('chromosome analyses'),
       ('chromosome banding'),
       ('chromosome banding'),
       ('chylomicrons'),
       ('chylomicrons'),
       ('chylous serum'),
       ('circulating anticoagulant'),
       ('circulating anticoagulant'),
       ('citric acid urine'),
       ('citric acid urine'),
       ('ck'),
       ('ck mb'),
       ('ck-mb'),
       ('ck2'),
       ('cl'),
       ('cl-'),
       ('clean-catch specimen of urine'),
       ('clostridium difficile toxin test'),
       ('clostridium difficile toxin test'),
       ('clot retraction'),
       ('clot retraction'),
       ('cmv igg antibody'),
       ('cmv igm antibody'),
       ('co2 tension'),
       ('coagulation and bleeding analyses'),
       ('coagulation factor'),
       ('coagulation factor'),
       ('coagulation factor ii level'),
       ('coagulation factor inhibitor assay'),
       ('coagulation factor inhibitor assay'),
       ('coagulation factor ix level'),
       ('coagulation factor ix level'),
       ('coagulation factor v level'),
       ('coagulation factor v level'),
       ('coagulation factor vii level'),
       ('coagulation factor vii level'),
       ('coagulation factor viii level'),
       ('coagulation factor viii level'),
       ('coagulation factor x level'),
       ('coagulation factor x level'),
       ('coagulation factor xi level'),
       ('coagulation factor xi level'),
       ('coagulation factor xii level'),
       ('coagulation factor xii level'),
       ('coagulation factor xiii level'),
       ('coagulation factor xiii level'),
       ('coagulation test'),
       ('coagulation test'),
       ('cold agglutinins'),
       ('cold agglutinins'),
       ('collagen antigen type 1'),
       ('collagen antigen type 1'),
       ('collagen antigen type iv'),
       ('collagen antigen type iv'),
       ('collagen cross-linked n-telopeptide'),
       ('complement factor'),
       ('complement factor'),
       ('complement factor c1'),
       ('complement factor c2'),
       ('complement factor c2'),
       ('complement factor c3'),
       ('complement factor c3'),
       ('complement factor c4'),
       ('complement factor c4'),
       ('complement factor nos'),
       ('complete blood count'),
       ('coombs direct test'),
       ('coombs direct test'),
       ('coombs indirect test'),
       ('coombs indirect test'),
       ('coombs test'),
       ('coombs test'),
       ('coombs test direct'),
       ('coombs test indirect'),
       ('coombs test nos'),
       ('copper'),
       ('cortical evoked response measurement'),
       ('cortical evoked response measurement'),
       ('corticosterone'),
       ('corticotrophin'),
       ('corticotropin'),
       ('cortisol'),
       ('cortisol free urine'),
       ('cortisol free urine'),
       ('coxsackie virus antibody test'),
       ('coxsackie virus serology test'),
       ('coxsackie virus serology test'),
       ('cpk'),
       ('cpk mb'),
       ('cpk-mb'),
       ('creatine'),
       ('creatine kinase'),
       ('creatine kinase mb'),
       ('creatine phosphokinase'),
       ('creatine phosphokinase mb'),
       ('creatine urine'),
       ('creatine urine'),
       ('creatinine'),
       ('creatinine clearance'),
       ('creatinine urine'),
       ('creatinine urine'),
       ('cross sensitivity react'),
       ('cross sensitivity reaction'),
       ('cross sensitivity reaction'),
       ('crossmatch'),
       ('crossmatch'),
       ('cryoglobulins'),
       ('cryoglobulins'),
       ('crystal urine'),
       ('crystal urine'),
       ('csf bacteria test'),
       ('csf bacteria test'),
       ('csf cell count'),
       ('csf cell count'),
       ('csf cell count nos'),
       ('csf culture'),
       ('csf culture'),
       ('csf electrophoresis'),
       ('csf electrophoresis'),
       ('csf fungus nos identified'),
       ('csf glucose'),
       ('csf glucose'),
       ('csf granulocyte count'),
       ('csf granulocyte count'),
       ('csf lactate'),
       ('csf lactate'),
       ('csf lactate dehydrogenase'),
       ('csf lactate dehydrogenase'),
       ('csf lymphocyte count'),
       ('csf lymphocyte count'),
       ('csf monocyte count'),
       ('csf monocyte count'),
       ('csf myelin basic protein'),
       ('csf myelin basic protein'),
       ('csf neutrophil count'),
       ('csf neutrophil count'),
       ('csf oligoclonal band'),
       ('csf oligoclonal band'),
       ('csf ph'),
       ('csf ph'),
       ('csf protein'),
       ('csf protein'),
       ('csf specific gravity'),
       ('csf specific gravity'),
       ('csf test'),
       ('csf test'),
       ('csf wbc'),
       ('csf white blood cell count'),
       ('csf white blood cell count'),
       ('csf white blood cell count nos'),
       ('csf white cell count nos'),
       ('cu'),
       ('cu++'),
       ('culture'),
       ('culture'),
       ('culture blood'),
       ('culture cervix'),
       ('culture cervix'),
       ('culture foreign body'),
       ('culture nos'),
       ('culture peritoneum'),
       ('culture pleural fluid'),
       ('culture stool'),
       ('culture stool'),
       ('culture throat'),
       ('culture throat'),
       ('culture tissue specimen'),
       ('culture tissue specimen'),
       ('culture urine'),
       ('culture urine'),
       ('culture wound'),
       ('culture wound'),
       ('cyclic amp'),
       ('cyclic amp'),
       ('cyclic amp urine'),
       ('cystatin c'),
       ('cystatin c'),
       ('cysteine urine'),
       ('cysteine urine'),
       ('cytogenetic investigations'),
       ('cytology'),
       ('cytology'),
       ('cytology nos'),
       ('cytomegalovirus antibody'),
       ('cytomegalovirus antibody'),
       ('cytomegalovirus antigen'),
       ('cytomegalovirus antigen'),
       ('cytomegalovirus serology'),
       ('cytomegalovirus serology'),
       ('cytomegalovirus serology nos'),
       ('cytomegalovirus test'),
       ('cytomegalovirus test'),
       ('cytomegalovirus test nos'),
       ('delta aminolevulinate urine'),
       ('deoxypyridinoline/creatinine ratio'),
       ('deoxypyridinoline/creatinine ratio'),
       ('dexamethasone suppression test'),
       ('dexamethasone suppression test'),
       ('differential wbc count'),
       ('differential white blood cell count'),
       ('differential white blood cell count'),
       ('digestive enzymes'),
       ('digitalis level'),
       ('dihydrotestosterone level'),
       ('dihydrotestosterone level'),
       ('diphtheria toxin antibody'),
       ('diphtheria toxin antibody'),
       ('direct coombs test'),
       ('direct immunofluorescence'),
       ('dna antibody'),
       ('dna antibody'),
       ('dna test for fragile x'),
       ('dna test for fragile x'),
       ('double stranded dna antibody'),
       ('double stranded dna antibody'),
       ('drug level'),
       ('drug level'),
       ('drug level nos'),
       ('drug screen'),
       ('drug screen'),
       ('drug-induced lymphocyte stimulation'),
       ('echo virus serology'),
       ('echovirus serology test'),
       ('echovirus serology test'),
       ('echovirus test'),
       ('ehrlichia dna test'),
       ('ehrlichia serology'),
       ('ehrlichia serology'),
       ('electron microscopy'),
       ('electron microscopy'),
       ('electrophoresis'),
       ('electrophoresis'),
       ('electrophoresis csf'),
       ('electrophoresis nos'),
       ('electrophoresis protein'),
       ('electrophoresis protein'),
       ('elisa'),
       ('endocrine test'),
       ('endocrine test'),
       ('endothelin'),
       ('endothelin'),
       ('enterovirus serology test'),
       ('enterovirus serology test'),
       ('enzyme investigations nec'),
       ('enzyme-linked immunosorbent assay'),
       ('eosinophil cationic protein'),
       ('eosinophil cationic protein'),
       ('eosinophil count'),
       ('eosinophil count'),
       ('eosinophil morphology'),
       ('eosinophil morphology'),
       ('eosinophil percentage'),
       ('eosinophil percentage'),
       ('epinephrine'),
       ('epinephrine'),
       ('epinephrine urine'),
       ('epstein-barr virus antibody'),
       ('epstein-barr virus antibody'),
       ('epstein-barr virus igm antibody'),
       ('epstein-barr virus serology'),
       ('epstein-barr virus test'),
       ('epstein-barr virus test'),
       ('erythroblast count'),
       ('erythroblast count'),
       ('erythroblast morphology'),
       ('erythroblast morphology'),
       ('erythrocyte osmotic fragility test'),
       ('erythrocyte osmotic fragility test'),
       ('estradiol'),
       ('estriol'),
       ('estriol urine'),
       ('estrogen'),
       ('estrogen receptor assay'),
       ('estrogens total urine'),
       ('estrone'),
       ('ethanol'),
       ('ethanol gelation test'),
       ('ethanol gelation test'),
       ('extractable nuclear antibody'),
       ('extravascular eosinophils'),
       ('factor rheumatoid'),
       ('faecal culture'),
       ('faecal occult blood'),
       ('fasting blood glucose'),
       ('fbc'),
       ('fdps'),
       ('fe'),
       ('fe++'),
       ('fe+++'),
       ('fecal culture'),
       ('fecal occult blood'),
       ('fetal hemoglobin'),
       ('fev'),
       ('fibrin'),
       ('fibrin'),
       ('fibrin d dimer'),
       ('fibrin d dimer'),
       ('fibrin degradation products'),
       ('fibrin degradation products'),
       ('fibrin split products'),
       ('fibrinogen'),
       ('fibrinolysis'),
       ('fibrinolysis'),
       ('filarial antibodies'),
       ('fletcher factor assay'),
       ('flow cytometry'),
       ('flow cytometry'),
       ('foetal haemoglobin'),
       ('foetal haemoglobin'),
       ('folate'),
       ('follicle stimulating hormone'),
       ('follitropin'),
       ('fractionated bile acids'),
       ('fractionated bile acids'),
       ('fragment d dimer'),
       ('free fatty acids'),
       ('free fatty acids'),
       ('free haemoglobin'),
       ('free haemoglobin'),
       ('free hemoglobin'),
       ('free t3'),
       ('free t4'),
       ('free thyroxine index'),
       ('free thyroxine index'),
       ('fructosamine'),
       ('fructosamine'),
       ('fructose'),
       ('fructose'),
       ('fsh'),
       ('fsps'),
       ('full blood count'),
       ('full blood count'),
       ('fungus csf test'),
       ('fungus csf test'),
       ('fungus identification and serology'),
       ('fungus serology test'),
       ('fungus serology test'),
       ('fungus sputum test'),
       ('fungus sputum test'),
       ('galactose elimination capacity test'),
       ('galactose elimination capacity test'),
       ('galactose tolerance test'),
       ('galactose urine'),
       ('galactose urine'),
       ('gamma globulin'),
       ('gamma glutamyl transpeptidase'),
       ('gamma gt'),
       ('gamma-glutamyltransferase'),
       ('gamma-glutamyltransferase'),
       ('gamma-glutamyltranspeptidase'),
       ('gastric fluid analysis'),
       ('gastric fluid analysis'),
       ('gastrin'),
       ('gastrointestinal, pancreatic and apu'),
       ('gene mutation identification test'),
       ('gene mutation identification test'),
       ('genotype drug resistance test'),
       ('genotype drug resistance test'),
       ('ggt'),
       ('ggtp'),
       ('gh'),
       ('giardiasis test'),
       ('globulin'),
       ('globulin'),
       ('globulin urine'),
       ('globulin urine'),
       ('glucagon'),
       ('glucagon tolerance test'),
       ('glucagon tolerance test'),
       ('glucose'),
       ('glucose urine'),
       ('glucose urine'),
       ('glucose-6-phosphate dehydrogenase'),
       ('glucose-6-phosphate dehydrogenase'),
       ('glutamate dehydrogenase'),
       ('glutamate dehydrogenase'),
       ('glutamic-oxaloacetic transferase'),
       ('glutamic-pyruvate transaminase'),
       ('glutathione test'),
       ('glutathione test'),
       ('glyceric acid urine'),
       ('glyceric acid urine'),
       ('glycohaemoglobin'),
       ('glycohemoglobin'),
       ('glycosylated haemoglobin'),
       ('glycosylated haemoglobin'),
       ('glycosylated hemoglobin'),
       ('gonadotrophin'),
       ('gonadotrophin releasing hormone stim'),
       ('gonadotrophin releasing hormone stim'),
       ('gonadotrophins'),
       ('gonadotropic follicle stimulating ho'),
       ('gonadotropic fsh'),
       ('gonadotropic luteinizing hormone'),
       ('gonadotropin releasing hormone stimu'),
       ('goodpastures antibody'),
       ('gpt'),
       ('gram stain'),
       ('gram stain'),
       ('granulocyte count'),
       ('granulocyte count'),
       ('granulocytic ehrlichiosis antibody'),
       ('group b betahaemolytic streptococcal'),
       ('group b betahemolytic streptococcal'),
       ('growth hormone'),
       ('growth hormone suppression test'),
       ('guthrie test'),
       ('haem metabolism analyses'),
       ('haematocrit'),
       ('haematocrit'),
       ('haematological analyses nec'),
       ('haematology test'),
       ('haematology test'),
       ('haemoconcentration'),
       ('haemoconcentration'),
       ('haemoglobin'),
       ('haemoglobin'),
       ('haemoglobin a2'),
       ('haemoglobin a2'),
       ('haemoglobin e'),
       ('haemoglobin e'),
       ('haemoglobin electrophoresis'),
       ('haemoglobin electrophoresis'),
       ('haemoglobin f'),
       ('haemoglobin glycosylated'),
       ('haemoglobin s'),
       ('haemoglobin s'),
       ('haemoglobin urine'),
       ('haemoglobin urine'),
       ('hair aluminium'),
       ('hair aluminum'),
       ('hair copper'),
       ('hair mercury'),
       ('hair metal test'),
       ('hair metal test'),
       ('hair sulfur'),
       ('hair zinc'),
       ('halothane antibodies'),
       ('halothane antibody'),
       ('halothane antibody'),
       ('ham test'),
       ('haptoglobin'),
       ('haptoglobin'),
       ('hav'),
       ('hba1c'),
       ('hbeag'),
       ('hbsag'),
       ('hbv'),
       ('hcv viral load'),
       ('hdl'),
       ('hdl/cholesterol ratio'),
       ('heaf test'),
       ('helicobacter pylori antibody'),
       ('helicobacter pylori identification t'),
       ('helicobacter pylori identification t'),
       ('helicobacter pylori urease test'),
       ('hematocrit'),
       ('hematology test'),
       ('hemoconcentration'),
       ('hemoglobin'),
       ('hemoglobin a2'),
       ('hemoglobin e'),
       ('hemoglobin electrophoresis'),
       ('hemoglobin f'),
       ('hemoglobin glycosylated'),
       ('hemoglobin s'),
       ('hemoglobin urine'),
       ('hepaplastin test'),
       ('hepaplastin test'),
       ('heparin-induced platelet activation'),
       ('heparin-induced platelet antibody'),
       ('heparin-induced thrombocytopenia tes'),
       ('heparin-induced thrombocytopenia tes'),
       ('hepatic enzyme'),
       ('hepatic enzyme'),
       ('hepatitis a antibodies'),
       ('hepatitis a antibody'),
       ('hepatitis a antibody'),
       ('hepatitis a igm'),
       ('hepatitis a screen'),
       ('hepatitis a virus'),
       ('hepatitis a virus'),
       ('hepatitis b antibody'),
       ('hepatitis b antibody'),
       ('hepatitis b antigen'),
       ('hepatitis b antigen'),
       ('hepatitis b core antigen'),
       ('hepatitis b core antigen'),
       ('hepatitis b dna assay'),
       ('hepatitis b dna assay'),
       ('hepatitis b e antigen'),
       ('hepatitis b e antigen'),
       ('hepatitis b screen'),
       ('hepatitis b surface antibody'),
       ('hepatitis b surface antigen'),
       ('hepatitis b surface antigen'),
       ('hepatitis b virus'),
       ('hepatitis b virus'),
       ('hepatitis b virus (hbv)'),
       ('hepatitis c antibody'),
       ('hepatitis c antibody'),
       ('hepatitis c rna'),
       ('hepatitis c rna'),
       ('hepatitis d antibody'),
       ('hepatitis d antibody'),
       ('hepatitis d rna'),
       ('hepatitis d rna'),
       ('hepatitis e antibody'),
       ('hepatitis e antibody'),
       ('hepatitis e antigen'),
       ('hepatitis e antigen'),
       ('hepatitis viral test'),
       ('hepatitis viral test'),
       ('hepatitis viral test nos'),
       ('hepatobiliary investigations'),
       ('herpes simplex antibody'),
       ('herpes simplex serology'),
       ('herpes simplex serology'),
       ('hess test'),
       ('high density lipoprotein'),
       ('high density lipoprotein'),
       ('high density lipoprotein cholesterol'),
       ('histamine level'),
       ('histamine level'),
       ('histamine urine'),
       ('histology'),
       ('histology'),
       ('histology nos'),
       ('histone antibody'),
       ('histone antibody'),
       ('hiv antibody'),
       ('hiv antibody'),
       ('hiv antigen (p24) test'),
       ('hiv ccr5 tropism'),
       ('hiv cxcr4 tropism'),
       ('hiv dual tropism'),
       ('hiv dual tropism positive'),
       ('hiv test'),
       ('hiv test'),
       ('hiv tests'),
       ('hiv tropism test'),
       ('hiv tropism test'),
       ('hiv viral load'),
       ('hiv-2 test'),
       ('hla marker study'),
       ('hla marker study'),
       ('hla marker tests nos'),
       ('homocysteine level'),
       ('human herpes virus 6 serology'),
       ('human herpes virus 6 serology'),
       ('human papilloma virus serology test'),
       ('human papilloma virus test'),
       ('human papilloma virus test'),
       ('hyaluronic acid'),
       ('hyaluronic acid'),
       ('hydrocortisone'),
       ('hydroxycorticosteroids urine'),
       ('hydroxycorticosteroids urine'),
       ('hydroxyproline'),
       ('hydroxyproline'),
       ('hydroxyproline urine'),
       ('icsh'),
       ('icterus index'),
       ('icterus index'),
       ('iga'),
       ('igd'),
       ('ige'),
       ('igg'),
       ('igm'),
       ('immune agglutinins'),
       ('immune agglutinins'),
       ('immune agglutinins nos'),
       ('immune complex assay'),
       ('immune complex assay'),
       ('immune complex formation'),
       ('immune response protein analyses nec'),
       ('immunoelectrophoresis'),
       ('immunoelectrophoresis'),
       ('immunofixation'),
       ('immunofluorescence'),
       ('immunogammaglobulin'),
       ('immunoglobulin a'),
       ('immunoglobulin analyses'),
       ('immunoglobulin e'),
       ('immunoglobulin g'),
       ('immunoglobulin m'),
       ('immunoglobulins'),
       ('immunoglobulins'),
       ('immunohistochemistry'),
       ('immunology and allergy investigation'),
       ('immunoreactive insulin'),
       ('immunosuppressant drug level'),
       ('immunosuppressant drug level'),
       ('immunosuppressant drug level nos'),
       ('indirect coombs test'),
       ('indirect immunofluorescence'),
       ('influenza a virus iga'),
       ('influenza a virus igg'),
       ('influenza a virus igm'),
       ('influenza antibody test'),
       ('influenza b virus iga'),
       ('influenza b virus igg'),
       ('influenza b virus igm'),
       ('influenza serology'),
       ('influenza serology'),
       ('inorganic phosphate'),
       ('inr'),
       ('insulin'),
       ('insulin c-peptide'),
       ('insulin c-peptide'),
       ('insulin tolerance test'),
       ('insulin tolerance test'),
       ('insulin-like growth factor'),
       ('insulin-like growth factor'),
       ('interferon alpha level'),
       ('interferon alpha level'),
       ('interferon gamma level'),
       ('interferon gamma level'),
       ('interleukin level'),
       ('interleukin level'),
       ('interleukin-13 level'),
       ('interleukin-6'),
       ('international normalised ratio'),
       ('international normalised ratio'),
       ('international normalized ratio'),
       ('interstitial cell-stimulating hormon'),
       ('intrinsic factor antibody'),
       ('intrinsic factor antibody'),
       ('inulin clearance'),
       ('inulin renal clearance'),
       ('inulin renal clearance'),
       ('iodine uptake'),
       ('iodine uptake'),
       ('ionized calcium'),
       ('ionized magnesium'),
       ('iron'),
       ('iron binding capacity total'),
       ('iron binding capacity total'),
       ('iron saturation'),
       ('isopropanol'),
       ('k'),
       ('k+'),
       ('kaolin cephalin clotting time'),
       ('kaolin cephalin clotting time'),
       ('kappa light chain analysis'),
       ('kappa/lambda light chain ratio'),
       ('karyotype analysis'),
       ('karyotype analysis'),
       ('karyotyping'),
       ('kcct'),
       ('ketone bodies'),
       ('ketones'),
       ('kl-6'),
       ('kleihauer-betke test'),
       ('kleihauer-betke test'),
       ('lab test'),
       ('laboratory test'),
       ('laboratory test'),
       ('lactate'),
       ('lactate dehydrogenase'),
       ('lactate dehydrogenase urine'),
       ('lactate dehydrogenase urine'),
       ('lactate pyruvate ratio'),
       ('lactate pyruvate ratio'),
       ('lactescent serum'),
       ('lactescent serum'),
       ('lactic acid'),
       ('lactose tolerance test'),
       ('lactose tolerance test'),
       ('lambda light chain analysis'),
       ('ldh'),
       ('ldl'),
       ('ldl/hdl ratio'),
       ('ldl/hdl ratio'),
       ('le cells'),
       ('le cells'),
       ('lead'),
       ('legionella nos antibody'),
       ('legionella nos serology test'),
       ('legionella serology'),
       ('legionella serology'),
       ('leucine aminopeptidase'),
       ('leucine aminopeptidase'),
       ('leukocyte count nos'),
       ('lh'),
       ('light chain analysis'),
       ('light chain analysis'),
       ('lipase'),
       ('lipase'),
       ('lipid analyses'),
       ('lipids'),
       ('lipids'),
       ('lipids nos'),
       ('lipoprotein (a)'),
       ('lipoprotein (a)'),
       ('lipoprotein and lipid tests nec'),
       ('liver function analyses'),
       ('liver function test'),
       ('liver function test'),
       ('liver function tests'),
       ('liver function tests nos'),
       ('liver pyruvate kinase'),
       ('liver-kidney microsomal antibody'),
       ('low density lipoprotein'),
       ('low density lipoprotein'),
       ('low density lipoprotein cholesterol'),
       ('lupus anticoagulant'),
       ('lutotropin'),
       ('lymphoblast count'),
       ('lymphoblast count'),
       ('lymphoblast morphology'),
       ('lymphoblast morphology'),
       ('lymphoblast morphology nos'),
       ('lymphocyte count'),
       ('lymphocyte count'),
       ('lymphocyte morphology'),
       ('lymphocyte morphology'),
       ('lymphocyte morphology nos'),
       ('lymphocyte percentage'),
       ('lymphocyte percentage'),
       ('lymphocyte stimulation test'),
       ('lymphocyte stimulation test'),
       ('lymphocyte transformation test'),
       ('lymphocyte transformation test'),
       ('lymphoscintigraphy radionuclide'),
       ('lysosomal enzyme analyses'),
       ('magnesium'),
       ('magnesium level'),
       ('malaria antibody test'),
       ('malaria antibody test'),
       ('manganese'),
       ('manganese'),
       ('marrow trephine'),
       ('mch'),
       ('mchc'),
       ('mean cell haemoglobin'),
       ('mean cell haemoglobin'),
       ('mean cell haemoglobin concentration'),
       ('mean cell haemoglobin concentration'),
       ('mean cell hemoglobin'),
       ('mean cell hemoglobin concentration'),
       ('mean cell volume'),
       ('mean cell volume'),
       ('mean corpuscular haemoglobin'),
       ('mean corpuscular hemoglobin'),
       ('mean corpuscular volume'),
       ('mean platelet volume'),
       ('mean platelet volume'),
       ('measles antibody'),
       ('measles antibody'),
       ('megakaryocytes'),
       ('megakaryocytes'),
       ('megaloblastosis'),
       ('metabolic function test'),
       ('metabolic function test'),
       ('metabolic function test nos'),
       ('metabolic, nutritional and blood gas'),
       ('metabolism tests nec'),
       ('metamyelocyte count'),
       ('metamyelocyte count'),
       ('metamyelocyte percentage'),
       ('metamyelocyte percentage'),
       ('metanephrine blood test'),
       ('metanephrine urine'),
       ('metanephrine urine'),
       ('methaemoglobin'),
       ('methaemoglobin urine'),
       ('methaemoglobin urine'),
       ('methemoglobin urine'),
       ('methicillin-resistant staphylococcal'),
       ('methicillin-resistant staphylococcal'),
       ('methylhistamine'),
       ('metopirone test'),
       ('metyrapone challenge test'),
       ('metyrapone challenge test'),
       ('mg++'),
       ('mha-tp'),
       ('microbiology and serology investigat'),
       ('microbiology and serology tests nec'),
       ('microbiology test'),
       ('microbiology test'),
       ('mid-stream specimen of urine'),
       ('mineral and electrolyte analyses'),
       ('minimum inhibitory concentration'),
       ('minimum inhibitory concentration'),
       ('mitochondria antibody'),
       ('mitogen stimulation test'),
       ('mitogen stimulation test'),
       ('mixed venous blood saturation'),
       ('mixed venous blood saturation'),
       ('molar ratio of total branched-chain'),
       ('molar ratio of total branched-chain'),
       ('monoblast count'),
       ('monoblast count'),
       ('monocyte count'),
       ('monocyte count'),
       ('monocyte morphology'),
       ('monocyte morphology'),
       ('monocyte percentage'),
       ('monocyte percentage'),
       ('monocytic ehrlichiosis antibody'),
       ('mononucleosis heterophile test'),
       ('mononucleosis heterophile test'),
       ('mssu'),
       ('mumps antibody test'),
       ('mumps antibody test'),
       ('muscle biopsy'),
       ('muscle enzyme'),
       ('muscle enzyme'),
       ('muscle relaxant drug level'),
       ('muscle relaxant drug level'),
       ('mycobacteria blood test'),
       ('mycobacteria identification and sero'),
       ('mycobacteria test'),
       ('mycobacteria test'),
       ('mycoplasma antibody'),
       ('mycoplasma serology'),
       ('mycoplasma serology'),
       ('myeloblast count'),
       ('myeloblast count'),
       ('myeloblast percentage'),
       ('myeloblast percentage'),
       ('myelocyte count'),
       ('myelocyte count'),
       ('myelocyte percentage'),
       ('myelocyte percentage'),
       ('myeloperoxidase antibody test'),
       ('myoglobin blood'),
       ('myoglobin blood'),
       ('myoglobin urine'),
       ('myoglobin urine'),
       ('n-telopeptide'),
       ('n-telopeptide'),
       ('n-telopeptide serum'),
       ('n-telopeptide urine'),
       ('n-telopeptide urine'),
       ('na+'),
       ('nasal septal biopsy'),
       ('neuron-specific enolase'),
       ('neuron-specific enolase'),
       ('neutrophil chemotaxis'),
       ('neutrophil chemotaxis'),
       ('neutrophil count'),
       ('neutrophil count'),
       ('neutrophil function test'),
       ('neutrophil function test'),
       ('neutrophil morphology'),
       ('neutrophil morphology'),
       ('neutrophil percentage'),
       ('neutrophil percentage'),
       ('newborn phenylketonuria screen'),
       ('nicotinamide'),
       ('nicotinamide'),
       ('nitrite urine'),
       ('nitrite urine'),
       ('non-high-density lipoprotein cholest'),
       ('non-high-density lipoprotein cholest'),
       ('non-protein nitrogen'),
       ('norepinephrine'),
       ('norepinephrine'),
       ('norepinephrine urine'),
       ('normetanephrine blood test'),
       ('nt-probnp'),
       ('nt-probnp'),
       ('nuclear antibody'),
       ('oestradiol'),
       ('oestradiol'),
       ('oestriol'),
       ('oestriol'),
       ('oestriol urine'),
       ('oestrogen'),
       ('oestrogen receptor assay'),
       ('oestrogen receptor assay'),
       ('oestrogens total urine'),
       ('oestrogens total urine'),
       ('oestrone'),
       ('oestrone'),
       ('opiates'),
       ('opiates'),
       ('osmolar gap'),
       ('osmolar gap'),
       ('osteocalcin'),
       ('osteocalcin'),
       ('osteoclast differentiation factor'),
       ('osteoprotegerin'),
       ('osteoprotegerin'),
       ('osteoprotegerin ligand'),
       ('osteoprotegerin ligand'),
       ('oxygen tension'),
       ('oxyhaemoglobin'),
       ('oxyhemoglobin'),
       ('oxytocin'),
       ('oxytocin'),
       ('p'),
       ('p+'),
       ('p24'),
       ('p24 antibody'),
       ('packed cell volume'),
       ('pancreatic enzymes'),
       ('pancreatic enzymes'),
       ('pancreatic enzymes nos'),
       ('pancreatic exocrine secretion test'),
       ('pandys test'),
       ('panel-reactive antibody'),
       ('panel-reactive antibody'),
       ('paracetamol'),
       ('paranasal biopsy'),
       ('paranasal biopsy'),
       ('parasite blood test'),
       ('parasite blood test'),
       ('parasite dna test'),
       ('parasite dna test'),
       ('parasite identification and serology'),
       ('parasite stool test'),
       ('parasite stool test'),
       ('parathormone'),
       ('parathyrn'),
       ('parathyroid hormone'),
       ('parathyroid hormone-related protein'),
       ('parathyroid hormone-related protein'),
       ('partial arterial pressure of carbon'),
       ('partial arterial pressure of oxygen'),
       ('partial pressure o2'),
       ('partial prothrombin time'),
       ('parvovirus b19 serology'),
       ('parvovirus b19 serology'),
       ('paul bunnell test'),
       ('paul-bunnell test'),
       ('pb'),
       ('pb++'),
       ('pcr'),
       ('pcv'),
       ('percussion test'),
       ('percussion test'),
       ('perinuclear antineutrophil cytoplasm'),
       ('peritoneal effluent analysis'),
       ('peritoneal effluent culture'),
       ('peritoneal fluid analysis'),
       ('peritoneal fluid analysis'),
       ('pertussis identification test'),
       ('pertussis identification test'),
       ('pertussis iga'),
       ('pertussis igg'),
       ('pertussis igm'),
       ('pertussis serology'),
       ('ph body fluid'),
       ('ph body fluid'),
       ('ph body fluid nos'),
       ('ph semen'),
       ('ph semen'),
       ('ph urine'),
       ('ph urine'),
       ('phenolsulfonphthalein test'),
       ('phenolsulfonphthalein test'),
       ('phenylalanine screen'),
       ('phenylalanine screen'),
       ('phosphate'),
       ('phosphate level'),
       ('phospholipid igg'),
       ('phospholipid igm'),
       ('phosphorus'),
       ('phytosterol level'),
       ('phytosterol level'),
       ('pituitary gonadotrophin'),
       ('pivka ii'),
       ('plasma acid phosphatase'),
       ('plasma albumin'),
       ('plasma aldosterone'),
       ('plasma alkaline phosphatase - bone'),
       ('plasma alkaline phosphatase - liver'),
       ('plasma alkaline phosphatase nos'),
       ('plasma amylase'),
       ('plasma bicarbonate'),
       ('plasma bilirubin'),
       ('plasma bilirubin direct'),
       ('plasma bilirubin indirect'),
       ('plasma bilirubin total'),
       ('plasma bromide'),
       ('plasma calcitonin'),
       ('plasma calcium'),
       ('plasma catecholamines'),
       ('plasma cell count'),
       ('plasma cell count'),
       ('plasma chloride'),
       ('plasma cholesterol'),
       ('plasma cholinesterase'),
       ('plasma copper'),
       ('plasma corticosterone'),
       ('plasma corticotrophin'),
       ('plasma cortisol'),
       ('plasma creatine'),
       ('plasma creatine phosphokinase'),
       ('plasma creatine phosphokinase mb'),
       ('plasma creatinine'),
       ('plasma electrolytes nos'),
       ('plasma estradiol'),
       ('plasma estrogen'),
       ('plasma fibrinogen'),
       ('plasma glucagon'),
       ('plasma gonadotrophin'),
       ('plasma growth hormone'),
       ('plasma immunoglobulin a'),
       ('plasma immunoglobulin e'),
       ('plasma immunoglobulin g'),
       ('plasma immunoglobulin m'),
       ('plasma insulin'),
       ('plasma iron'),
       ('plasma lactate dehydrogenase'),
       ('plasma lactic acid'),
       ('plasma lead'),
       ('plasma luteinising hormone'),
       ('plasma magnesium'),
       ('plasma oestradiol'),
       ('plasma oestrogen'),
       ('plasma osmolarity'),
       ('plasma ph nos'),
       ('plasma phosphate'),
       ('plasma potassium'),
       ('plasma prolactin'),
       ('plasma protein'),
       ('plasma protein / albumin'),
       ('plasma pyruvic acid'),
       ('plasma selenium'),
       ('plasma sodium'),
       ('plasma testosterone'),
       ('plasma thrombin'),
       ('plasma thromboplastin'),
       ('plasma thyroid stimulating hormone'),
       ('plasma triglycerides'),
       ('plasma urea'),
       ('plasma uric acid'),
       ('plasma viscosity'),
       ('plasma viscosity'),
       ('plasma zinc'),
       ('plasmablast count'),
       ('plasmablast count'),
       ('plasmin inhibitor'),
       ('plasmin inhibitor'),
       ('plasminogen'),
       ('plasminogen'),
       ('plasminogen activator inhibitor'),
       ('plasminogen activator inhibitor'),
       ('platelet aggregation nos'),
       ('platelet analyses'),
       ('platelet count'),
       ('platelet count'),
       ('platelet distribution width'),
       ('platelet distribution width'),
       ('platelet factor 4'),
       ('platelet factor 4'),
       ('platelet function test'),
       ('platelet function test'),
       ('platelet morphology'),
       ('platelet morphology'),
       ('plateletcrit'),
       ('plateletcrit'),
       ('pleocytosis'),
       ('pleocytosis'),
       ('po2'),
       ('po2'),
       ('poliovirus serology'),
       ('poliovirus serology'),
       ('polyclonal gammaglobulins'),
       ('polymerase chain reaction'),
       ('polymerase chain reaction'),
       ('polymorphonuclear count'),
       ('porphyria screen'),
       ('porphyria screen'),
       ('porphyrins urine'),
       ('porphyrins urine'),
       ('potassium'),
       ('potassium hydroxide preparation'),
       ('potassium hydroxide preparation'),
       ('prealbumin'),
       ('prealbumin'),
       ('pregnancy test urine'),
       ('pregnancy test urine'),
       ('prekallikrein screen'),
       ('prekallikrein test'),
       ('prekallikrein test'),
       ('pro-thrombin time'),
       ('procalcitonin'),
       ('procalcitonin'),
       ('procollagen type i c-terminal propep'),
       ('procollagen type i c-terminal propep'),
       ('proerythroblast count'),
       ('proerythroblast count'),
       ('progesterone'),
       ('progesterone'),
       ('progesterone receptor assay'),
       ('progesterone receptor assay'),
       ('proinsulin'),
       ('prolactin'),
       ('promyelocyte count'),
       ('promyelocyte count'),
       ('prostatic acid phosphatase'),
       ('prostatic acid phosphatase'),
       ('prostatic specific antigen'),
       ('prostatic specific antigen'),
       ('protein'),
       ('protein albumin ratio'),
       ('protein albumin ratio'),
       ('protein analyses nec'),
       ('protein and chemistry analyses nec'),
       ('protein bound iodine'),
       ('protein bound iodine'),
       ('protein bound iodine serum'),
       ('protein c'),
       ('protein c'),
       ('protein c antigen'),
       ('protein induced by vitamin k absence'),
       ('protein induced by vitamin k absence'),
       ('protein nos'),
       ('protein s'),
       ('protein s'),
       ('protein s antigen'),
       ('protein s free'),
       ('protein s total'),
       ('protein total'),
       ('protein total'),
       ('protein urine'),
       ('protein urine'),
       ('protein urine 24 hour'),
       ('proteinase-3 antibody'),
       ('prothrombin'),
       ('prothrombin activity'),
       ('prothrombin level'),
       ('prothrombin level'),
       ('prothrombin test'),
       ('prothrombin time'),
       ('prothrombin time'),
       ('prothrombin time test'),
       ('psa'),
       ('pseudocholinesterase'),
       ('pseudothrombocytopenia'),
       ('psp test'),
       ('pth'),
       ('pyridinoline urine'),
       ('pyridinoline urine'),
       ('pyruvate'),
       ('pyruvate kinase'),
       ('pyruvate kinase'),
       ('pyruvic acid'),
       ('quicks test'),
       ('ra latex test'),
       ('radioallergosorbent test'),
       ('radioallergosorbent test'),
       ('rapid plasma reagin test'),
       ('rapid streptococcal test'),
       ('rast'),
       ('rbc count'),
       ('red blood cell analyses'),
       ('red blood cell analysis'),
       ('red blood cell analysis'),
       ('red blood cell cholinesterase'),
       ('red blood cell count'),
       ('red blood cell count'),
       ('red blood cell microcytes'),
       ('red blood cell microcytes'),
       ('red blood cell morphology'),
       ('red blood cell morphology'),
       ('red blood cells semen'),
       ('red blood cells semen'),
       ('red cell distribution width'),
       ('red cell distribution width'),
       ('renal function analyses'),
       ('renal function test'),
       ('renal function test'),
       ('renal function tests nos'),
       ('renin'),
       ('renin'),
       ('reproductive hormone'),
       ('reproductive hormone'),
       ('reticulocyte count'),
       ('reticulocyte count'),
       ('reticulocyte percentage'),
       ('reticulocyte percentage'),
       ('retinal biopsy'),
       ('retinol binding protein'),
       ('retinol binding protein'),
       ('reverse t3'),
       ('reverse tri-iodothyronine'),
       ('reverse tri-iodothyronine'),
       ('rhesus antibodies'),
       ('rhesus antibodies'),
       ('rheumatoid factor'),
       ('rheumatoid factor'),
       ('rheumatoid factor quantitative'),
       ('rheumatoid factor quantitative'),
       ('riboflavin'),
       ('ribonucleoprotein antibody'),
       ('rickettsia antibody'),
       ('rickettsia antibody'),
       ('rickettsia nos antibody'),
       ('rickettsia typhi igg'),
       ('rickettsia typhi igm'),
       ('ross river virus serology test'),
       ('rotavirus test'),
       ('rotavirus test'),
       ('rpr'),
       ('rsv serology'),
       ('rubella antibody test'),
       ('rubella antibody test'),
       ('rubella immunity status'),
       ('rubeola antibodies nos'),
       ('rubeola antibody'),
       ('rubeola antibody nos'),
       ('rumpel-leede reaction'),
       ('russells viper venom time'),
       ('russells viper venom time'),
       ('salicylate'),
       ('saliva alcohol test'),
       ('saliva alcohol test'),
       ('saliva analysis'),
       ('saliva analysis'),
       ('scan lymph nodes'),
       ('scan lymph nodes'),
       ('scan nos lymph nodes'),
       ('schistosoma serology'),
       ('schistosoma test'),
       ('schistosoma test'),
       ('schlichter test'),
       ('schumms test'),
       ('schumms test'),
       ('scleral biopsy'),
       ('screening neural tube defect (matern'),
       ('se'),
       ('se++'),
       ('secretin test'),
       ('secretin test'),
       ('segmented neutrophil count'),
       ('selenium'),
       ('semen liquefaction'),
       ('semen liquefaction'),
       ('seroconversion test'),
       ('seroconversion test'),
       ('serology nos'),
       ('serology test'),
       ('serology test'),
       ('serum acid phosphatase'),
       ('serum albumin'),
       ('serum aldosterone'),
       ('serum alkaline phosphatase - bone'),
       ('serum alkaline phosphatase - liver'),
       ('serum alkaline phosphatase nos'),
       ('serum amylase'),
       ('serum bactericidal titer'),
       ('serum bicarbonate'),
       ('serum bilirubin'),
       ('serum bilirubin direct'),
       ('serum bilirubin indirect'),
       ('serum bilirubin total'),
       ('serum bromide'),
       ('serum calcitonin'),
       ('serum calcium'),
       ('serum catecholamines'),
       ('serum chloride'),
       ('serum cholesterol'),
       ('serum cholinesterase'),
       ('serum copper'),
       ('serum corticosterone'),
       ('serum corticotrophin'),
       ('serum cortisol'),
       ('serum creatine'),
       ('serum creatine phosphokinase'),
       ('serum creatine phosphokinase mb'),
       ('serum creatinine'),
       ('serum electrolytes nos'),
       ('serum estradiol'),
       ('serum estrogen'),
       ('serum ferritin'),
       ('serum ferritin'),
       ('serum follicle stimulating hormone'),
       ('serum glucagon'),
       ('serum glucose'),
       ('serum glutamic-oxaloacetic transfera'),
       ('serum gonadotrophin'),
       ('serum growth hormone'),
       ('serum immunoglobulin a'),
       ('serum immunoglobulin e'),
       ('serum immunoglobulin g'),
       ('serum immunoglobulin m'),
       ('serum insulin'),
       ('serum iron'),
       ('serum lactate dehydrogenase'),
       ('serum lactic acid'),
       ('serum ldh'),
       ('serum lead'),
       ('serum luteinising hormone'),
       ('serum magnesium'),
       ('serum oestradiol'),
       ('serum oestrogen'),
       ('serum osmolality'),
       ('serum parathyroid hormone'),
       ('serum ph nos'),
       ('serum phosphate'),
       ('serum potassium'),
       ('serum procollagen type iii n-termina'),
       ('serum procollagen type iii n-termina'),
       ('serum prolactin'),
       ('serum protein / albumin'),
       ('serum protein electrophoresis'),
       ('serum pyruvic acid'),
       ('serum selenium'),
       ('serum sodium'),
       ('serum testosterone'),
       ('serum thyroid stimulating hormone'),
       ('serum triglycerides'),
       ('serum urea'),
       ('serum uric acid'),
       ('serum zinc'),
       ('sex hormone binding globulin'),
       ('sex hormone binding globulin'),
       ('sgot'),
       ('sgpt'),
       ('skeletal and cardiac muscle analyses'),
       ('skeletal muscle enzymes'),
       ('skeletal muscle enzymes'),
       ('skeletal muscle enzymes nos'),
       ('sm antibody'),
       ('smooth muscle antibody'),
       ('smooth muscle antibody'),
       ('sodium'),
       ('soluble fibrin monomer'),
       ('somatomedin c'),
       ('somatotrophic hormone'),
       ('somatotrophin'),
       ('somatotropin'),
       ('somatotropin suppression test'),
       ('somatotropin suppression test'),
       ('specific gravity body fluid'),
       ('specific gravity body fluid'),
       ('specific gravity body fluid nos'),
       ('specific gravity urine'),
       ('specific gravity urine'),
       ('spep'),
       ('sperm analysis'),
       ('sperm analysis'),
       ('sperm count'),
       ('sperm count'),
       ('spinal fluid culture'),
       ('spleen scintigraphy'),
       ('sputum culture'),
       ('sputum culture'),
       ('sputum test'),
       ('sputum test'),
       ('srankl'),
       ('staphylococcal identification test'),
       ('staphylococcal identification test'),
       ('staphylococcal serology'),
       ('sth'),
       ('stool analysis'),
       ('stool analysis'),
       ('stool culture'),
       ('stool guaiac test'),
       ('stool haemoglobin-haptoglobin comple'),
       ('stool haemoglobin-haptoglobin comple'),
       ('stool hemoglobin-haptoglobin complex'),
       ('streptococcal identification test'),
       ('streptococcal identification test'),
       ('streptococcal serology'),
       ('streptolysin o antibody'),
       ('streptozyme test'),
       ('sucrose haemolysis test'),
       ('sucrose hemolysis test'),
       ('svo2'),
       ('sweat chloride test'),
       ('sweat chloride test'),
       ('synacthen test'),
       ('synovial fluid analysis'),
       ('synovial fluid analysis'),
       ('synovial fluid cell count'),
       ('synovial fluid cell count'),
       ('synovial fluid color'),
       ('synovial fluid colour'),
       ('synovial fluid culture'),
       ('synovial fluid gram stain'),
       ('syphilis test'),
       ('syphilis test'),
       ('syphilis test nos'),
       ('t-lymphocyte count'),
       ('t-lymphocyte count'),
       ('t3'),
       ('t3 uptake'),
       ('t3u'),
       ('t4'),
       ('tbg'),
       ('tct'),
       ('test thymol turbidity'),
       ('testosterone'),
       ('tetanus antibody'),
       ('tetanus antibody'),
       ('tfts'),
       ('therapeutic drug monitoring analyses'),
       ('thiamine'),
       ('thrombin'),
       ('thrombin clotting time'),
       ('thrombin time'),
       ('thrombin time'),
       ('thrombin-antithrombin iii complex'),
       ('thrombin-antithrombin iii complex'),
       ('thrombocyte count'),
       ('thromboplastin'),
       ('thromboplastin antibody'),
       ('thromboplastin antibody'),
       ('thymol turbidity test'),
       ('thymol turbidity test'),
       ('thyroglobulin'),
       ('thyroglobulin'),
       ('thyroglobulin antibody'),
       ('thyroid analyses'),
       ('thyroid binding globulin'),
       ('thyroid function test'),
       ('thyroid function test'),
       ('thyroid function tests nos'),
       ('thyroid hormone binding index'),
       ('thyroid microsome antibody'),
       ('thyroid releasing hormone challenge'),
       ('thyroid releasing hormone challenge'),
       ('thyroid stimulating hormone'),
       ('thyrotrophin'),
       ('thyrotropin'),
       ('thyroxin binding globulin'),
       ('thyroxin binding globulin'),
       ('thyroxine'),
       ('thyroxine'),
       ('thyroxine free'),
       ('thyroxine free'),
       ('tissue enzyme analyses nec'),
       ('tissue polypeptide antigen'),
       ('tissue polypeptide antigen'),
       ('total bile acids'),
       ('total bile acids'),
       ('total cholesterol/hdl ratio'),
       ('total cholesterol/hdl ratio'),
       ('total iron binding capacity'),
       ('total phospholipids'),
       ('total white blood cell count'),
       ('toxicologic test'),
       ('toxicologic test'),
       ('toxicology and therapeutic drug moni'),
       ('toxicology laboratory analyses'),
       ('toxicology nos'),
       ('toxoplasma serology'),
       ('toxoplasma serology'),
       ('transaminase nos'),
       ('transaminases'),
       ('transaminases'),
       ('transferrin'),
       ('transferrin'),
       ('transferrin saturation'),
       ('transferrin saturation'),
       ('transtubular potassium gradient'),
       ('transtubular potassium gradient'),
       ('treponema pallidum antibody'),
       ('tri-iodothyronine'),
       ('tri-iodothyronine'),
       ('tri-iodothyronine free'),
       ('tri-iodothyronine free'),
       ('tri-iodothyronine uptake'),
       ('tri-iodothyronine uptake'),
       ('tricyclic antidepressant level'),
       ('triglyceride analyses'),
       ('triglycerides'),
       ('troponin'),
       ('troponin'),
       ('troponin i'),
       ('troponin i'),
       ('troponin nos'),
       ('troponin t'),
       ('troponin t'),
       ('tryptase'),
       ('tryptase'),
       ('tsh'),
       ('tumor marker test'),
       ('tumour cell marker test nos'),
       ('tumour marker test'),
       ('tumour marker test'),
       ('urea'),
       ('urea urine'),
       ('urea urine'),
       ('uric acid'),
       ('urinalysis'),
       ('urinalysis nec'),
       ('urinary 6 beta hydroxycortisol/corti'),
       ('urinary 6 beta hydroxycortisol/corti'),
       ('urinary aldosterone'),
       ('urinary free cortisol'),
       ('urinary haemoglobin'),
       ('urinary hemoglobin'),
       ('urine albumin/creatinine ratio'),
       ('urine albumin/creatinine ratio'),
       ('urine alcohol test'),
       ('urine alcohol test'),
       ('urine aluminium'),
       ('urine aluminium'),
       ('urine aluminum'),
       ('urine amino acid level'),
       ('urine amino acid level'),
       ('urine aminolevulinic acid'),
       ('urine amphetamine'),
       ('urine amphetamine'),
       ('urine amylase'),
       ('urine amylase'),
       ('urine analysis'),
       ('urine analysis'),
       ('urine antimony'),
       ('urine antimony'),
       ('urine arsenic'),
       ('urine arsenic'),
       ('urine barbiturates'),
       ('urine barbiturates'),
       ('urine beryllium'),
       ('urine beryllium'),
       ('urine calcium'),
       ('urine calcium'),
       ('urine casomorphin'),
       ('urine casomorphin'),
       ('urine chloride'),
       ('urine chloride'),
       ('urine chromium'),
       ('urine chromium'),
       ('urine copper'),
       ('urine copper'),
       ('urine cortisol/creatinine ratio'),
       ('urine cortisol/creatinine ratio'),
       ('urine cotinine test'),
       ('urine cotinine test'),
       ('urine culture'),
       ('urine cytology'),
       ('urine cytology'),
       ('urine delta aminolevulinate'),
       ('urine delta aminolevulinate'),
       ('urine dihydrotestosterone'),
       ('urine drug screen'),
       ('urine electrolytes'),
       ('urine electrolytes'),
       ('urine electrolytes nos'),
       ('urine electrophoresis'),
       ('urine electrophoresis'),
       ('urine glucose'),
       ('urine ketone body'),
       ('urine ketone body'),
       ('urine lactic acid'),
       ('urine lactic acid'),
       ('urine leucine'),
       ('urine leukocyte esterase'),
       ('urine leukocyte esterase'),
       ('urine mercury'),
       ('urine mercury'),
       ('urine methylhistamine'),
       ('urine microalbumin'),
       ('urine nitrogen'),
       ('urine nitrogen'),
       ('urine osmolality'),
       ('urine osmolarity'),
       ('urine osmolarity'),
       ('urine osmotic pressure'),
       ('urine oxalate'),
       ('urine oxalate'),
       ('urine oxalate, quantitative'),
       ('urine ph'),
       ('urine phosphate'),
       ('urine phosphate'),
       ('urine phosphorus'),
       ('urine potassium'),
       ('urine potassium'),
       ('urine protein, quantitative'),
       ('urine protein, quantitative'),
       ('urine protein/creatinine ratio'),
       ('urine protein/creatinine ratio'),
       ('urine retinol binding protein'),
       ('urine retinol binding protein'),
       ('urine selenium'),
       ('urine selenium'),
       ('urine sodium'),
       ('urine sodium'),
       ('urine specific gravity'),
       ('urine uric acid'),
       ('urine uric acid'),
       ('urine uric acid, quantitative'),
       ('urine viscosity'),
       ('urine viscosity'),
       ('urobilin urine'),
       ('urobilin urine'),
       ('urobilinogen'),
       ('urobilinogen faeces'),
       ('urobilinogen faeces'),
       ('urobilinogen feces'),
       ('urobilinogen urine'),
       ('urobilinuria'),
       ('urobilinuria'),
       ('uroporphyrin'),
       ('vanillyl mandelic acid urine'),
       ('vanillyl mandelic acid urine'),
       ('vasoactive intestinal polypeptide te'),
       ('vasoactive intestinal polypeptide te'),
       ('vasopressin'),
       ('vc'),
       ('vdrl'),
       ('very low density lipoprotein'),
       ('very low density lipoprotein'),
       ('very low density lipoprotein cholest'),
       ('vip test'),
       ('viral load'),
       ('viral load'),
       ('viral load nos'),
       ('viral test'),
       ('viral test'),
       ('virus antibody test nos'),
       ('virus body fluid identified'),
       ('virus body fluid identified'),
       ('virus culture'),
       ('virus culture'),
       ('virus identification and serology'),
       ('virus nos body fluid identified'),
       ('virus serology test'),
       ('virus serology test'),
       ('virus serology test nos'),
       ('virus stool test'),
       ('virus stool test'),
       ('virus urine test'),
       ('virus urine test'),
       ('vital capacity'),
       ('vital capacity'),
       ('vitamin a'),
       ('vitamin a'),
       ('vitamin analyses'),
       ('vitamin b1'),
       ('vitamin b1'),
       ('vitamin b12'),
       ('vitamin b12'),
       ('vitamin b2'),
       ('vitamin b2'),
       ('vitamin b3'),
       ('vitamin b6'),
       ('vitamin b6'),
       ('vitamin c'),
       ('vitamin c'),
       ('vitamin d'),
       ('vitamin d'),
       ('vitamin e'),
       ('vitamin e'),
       ('vitamin k'),
       ('vitamin k'),
       ('vldl'),
       ('von willebrands factor multimers te'),
       ('von willebrands factor multimers te'),
       ('waaler-rose test'),
       ('water and electrolyte analyses nec'),
       ('water, electrolyte and mineral inves'),
       ('wbc count'),
       ('western blot for hiv'),
       ('western blot test'),
       ('white blood cell analyses'),
       ('white blood cell analysis'),
       ('white blood cell analysis'),
       ('white blood cell count'),
       ('white blood cell count'),
       ('white blood cell count nos'),
       ('white blood cell count nos csf'),
       ('white blood cell morphology'),
       ('white blood cell morphology'),
       ('white blood cells semen'),
       ('white blood cells semen'),
       ('white blood cells stool'),
       ('white blood cells stool'),
       ('white blood cells urine'),
       ('white blood cells urine'),
       ('white cells'),
       ('x-ray of nasolacrimal duct'),
       ('yersinia serology'),
       ('zinc'),
       ('zinc sulphate turbidity test'),
       ('zinc sulphate turbidity test'),
       ('zn'),
       ('zn++');
